name: chatbot-rag-fptu-sdn

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: chatbot-rag-postgres-sdn
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: chatbot-rag-redis-sdn
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm-sdn
    restart: always
    ports:
      - "3004:3001"
    environment:
      - STORAGE_DIR=/app/server/storage
    volumes:
      - anythingllm_storage:/app/server/storage

volumes:
  postgres_data:
  redis_data:
  anythingllm_storage:
